from pathlib import Path
import json, html
from PIL import Image
R=Path(__file__).resolve().parents[1]; S=R/'samples/sample-3-studio'
d=json.loads((S/'facts.json').read_text()); esc=html.escape
nav=[('index.html','Gather'),('menu.html','The menu'),('gallery.html','In good company'),('story.html','Meet Tricia'),('enquire.html','Make it yours')]
def img(f,alt,cls=''):
 w,h=Image.open(S/'img'/f).size
 return f'<img class="{cls}" src="img/{f}" alt="{esc(alt)}" width="{w}" height="{h}">'
def page(file,title,body):
 active=''.join(f'<a href="{url}" '+('aria-current="page"' if url==file else '')+f'>{label}</a>' for url,label in nav)
 text=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} | The Chick Goodies</title><meta name="description" content="Gather around charcuterie, generous grazing tables and food made for your occasion. Meet Tricia Holfelder and plan your gathering in Tomball, Texas."><link rel="stylesheet" href="gathering.css"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=Playfair+Display:ital,wght@0,500;0,700;1,500&display=swap" rel="stylesheet"></head><body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="index.html">{img('brand.webp','The Chick Goodies — home')}</a><nav aria-label="Main navigation">{active}</nav></header><main id="main">{body}</main><footer><div><a class="brand" href="index.html">{img('brand.webp','The Chick Goodies')}</a><p>Tomball · The Woodlands · Spring · Conroe</p></div><a class="footer-invite" href="enquire.html">There’s a place<br>for your people. ↗</a><div><a href="tel:+{esc(d['phone'])}">Call Tricia</a> · <a href="mailto:{esc(d['email'])}">Email Tricia</a><p>Food. Company. A reason to gather.</p></div></footer><script src="gathering.js" defer></script></body></html>'''
 (S/file).write_text(text,encoding='utf-8')
body=f'''<section class="hero"><div class="hero-top"><p class="eyebrow">Tomball, Texas / Made for your people</p><button id="motion" type="button" aria-pressed="false">Pause motion</button></div><h1>Good food.<br><em>Better company.</em></h1><div class="table-world"><canvas id="table-scene" aria-label="Interactive sculptural table setting"></canvas><div class="scene-fallback" aria-hidden="true"><i></i><i></i><i></i></div><p class="scene-label">A place for everyone.</p></div><div class="hero-bottom"><p>Not just something to eat.<br>Something to gather around.</p><a class="pill" href="enquire.html">Set something in motion <span>↗</span></a><span class="scroll-note">Scroll to pull up a chair ↓</span></div></section><section class="intro"><p class="eyebrow">01 / The art of coming together</p><div class="intro-type"><h2>A little occasion.<br>A <em>lot</em> of goodness.</h2><p>Grazing tables, charcuterie carts and boards. Built around the people you’re bringing together.</p><a class="line-link" href="menu.html">Find your kind of feast ↗</a></div><figure class="photo-tilt">{img('knot-hero.jpg','A real Charcuterie Chick grazing display')}<figcaption>From Tricia’s table, to yours.</figcaption></figure></section><section class="occasion"><p class="eyebrow">02 / What brings you together?</p><div class="occasion-layout"><div class="occasion-buttons"><button data-occasion="Wedding" aria-pressed="true">We’re saying<br><em>“I do.”</em><span>01</span></button><button data-occasion="Celebration" aria-pressed="false">Just because.<span>02</span></button><button data-occasion="Work gathering" aria-pressed="false">Out of office.<span>03</span></button></div><div class="occasion-detail"><p id="occasion-copy" aria-live="polite">A wedding brings everyone to one table. Let’s make it yours.</p><a id="occasion-link" class="pill" href="enquire.html?occasion=Wedding">Plan this gathering ↗</a>{img('cart-640.jpg','Charcuterie Chick cart at an event')}</div></div></section><section class="closing"><p class="eyebrow">03 / The woman behind the welcome</p><h2>Hi, I’m <em>Tricia.</em></h2><p>More than 35 years in the restaurant industry.<br>One party at a time.</p><a class="line-link" href="story.html">Come meet your host ↗</a></section><script type="module" src="table-scene.js"></script>'''
page('index.html','A reason to gather',body)
menu=''.join(f'''<article class="menu-item" id="{m['id']}"><span class="menu-number">0{i+1}</span><div><h2>{esc(m['name'])}</h2><p>{esc(m['description'])}</p><a class="line-link" href="enquire.html?table={m['id']}">This is our table ↗</a></div><p class="price">{esc(m['price'])}</p></article>''' for i,m in enumerate(d['menus']))
page('menu.html','The menu',f'''<section class="page-head"><p class="eyebrow">The menu / A little of everything</p><h1>More to<br><em>come together for.</em></h1><p>Start with the table. Make it your occasion.</p></section><section class="menu-intro">{img('knot-2.jpg','A plentiful Charcuterie Chick spread')}<div><p>Per-person grazing tables have a 50-guest minimum. All table services run 90 minutes.</p><p>Published food prices below exclude the $229 setup fee and 18% tax. Extra service time is $3 per person per half hour. Final details confirmed by Tricia.</p></div></section><section class="menu-list">{menu}</section><section class="closing"><h2>A different<br><em>kind of gathering?</em></h2><p>Ask about boards, carts, sweets and sips. Boards are priced on request.</p><a class="pill" href="enquire.html">Let’s make a plan ↗</a></section>''')
gallery=[('knot-hero.jpg','The gathering table'),('board-01.jpg','A closer look'),('cart-640.jpg','Good things on wheels'),('sips-01.jpg','Raise a glass'),('knot-3.jpg','A generous welcome'),('sweets-01.jpg','Something sweet')]
items=''.join(f'''<figure><a href="img/{f}" data-lightbox data-caption="{caption}">{img(f,'Charcuterie Chick: '+caption)}<span>View photograph ↗</span></a><figcaption>0{i+1} / {caption}</figcaption></figure>''' for i,(f,caption) in enumerate(gallery))
page('gallery.html','In good company',f'''<section class="page-head"><p class="eyebrow">Real food / Real occasions</p><h1>Wish you<br><em>were here.</em></h1><p>A few moments from the table. Explore the photographs.</p></section><section class="gallery-wall">{items}</section><dialog id="lightbox"><button id="close-gallery" aria-label="Close photograph">Close ×</button><img id="large-photo" src="img/knot-hero.jpg" width="945" height="720" alt="Charcuterie Chick gathering"><p id="photo-caption"></p><div><button id="previous-photo">← Previous</button><button id="next-photo">Next →</button></div></dialog>''')
page('story.html','Meet Tricia',f'''<section class="story-head"><div><p class="eyebrow">Your host / Tricia Holfelder</p><h1>A little heart.<br><em>In every gathering.</em></h1></div>{img('tricia-662.jpg','Tricia Holfelder, owner of Charcuterie Chick')}</section><section class="story-letter"><p class="eyebrow">A welcome from Tomball, Texas</p><h2>The food matters.<br><em>So do the people.</em></h2><p>Tricia brings more than 35 years in the restaurant industry, working both front-of-house and back-of-house, to Charcuterie Chick.</p><p>Scratch-made breads, jellies and jams. Grazing tables and charcuterie carts. One party at a time.</p><p>From Tomball to The Woodlands, Spring and Conroe, it starts with your occasion and the people you want around the table.</p><a class="pill" href="enquire.html">Tell Tricia what you’re planning ↗</a></section>''')
options=''.join(f'<option value="{m["id"]}">{esc(m["name"])}</option>' for m in d['menus'])
page('enquire.html','Make it yours',f'''<section class="page-head compact"><p class="eyebrow">Your gathering starts here</p><h1>Pull up<br><em>a few chairs.</em></h1><p>Explore an estimate. Then talk to Tricia. No payment, no booking, no message sent automatically.</p></section><section class="planner"><div class="planner-inputs"><label for="occasion">The occasion</label><select id="occasion"><option>Wedding</option><option>Celebration</option><option>Work gathering</option><option>Something else</option></select><label for="table">Your table</label><select id="table">{options}</select><label for="guests">How many people?</label><div class="stepper"><button id="fewer" aria-label="Fewer guests">−</button><input id="guests" type="number" min="50" max="1000" value="75" step="1"><button id="more" aria-label="More guests">+</button></div><p id="guest-hint">Holy Grail: published packages for 75 or 150 guests.</p><label for="date">Your date (optional)</label><input id="date" type="date"><label for="notes">Anything Tricia should know? (optional)</label><textarea id="notes" rows="3" maxlength="1500" placeholder="Venue, dietary needs, or a little about your plans"></textarea></div><div class="planner-output"><div id="seats" aria-hidden="true"></div><p class="eyebrow">90-minute gathering / Estimated total</p><output id="total" aria-live="polite">Ask Tricia</output><p id="quote-error" role="status"></p><dl><div><dt>Food</dt><dd id="food">—</dd></div><div><dt>Setup</dt><dd>$229.00</dd></div><div><dt>18% tax estimate</dt><dd id="tax">—</dd></div></dl><p class="fine">Tax is estimated on food + setup; this basis needs confirmation. Extra time excluded. Published prices are subject to Tricia’s final quote and availability.</p><div class="contact-actions"><a class="pill" id="email-enquiry" href="mailto:{esc(d['email'])}">Open email enquiry ↗</a><a class="line-link" id="text-enquiry" href="sms:+{esc(d['phone'])}">Open text enquiry ↗</a><a class="line-link" href="tel:+{esc(d['phone'])}">Or call Tricia ↗</a></div><noscript><p>The calculator needs JavaScript. Call or email Tricia above for a quote; the full published menu is available on the menu page.</p></noscript></div></section>''')
print('Wrote five gathering pages')
